# Statically link the MSVC C runtime so the produced .exe is fully self-contained.
# This removes the runtime dependency on the Visual C++ Redistributable
# (vcruntime140.dll), so the program runs on a clean Windows 10 / 11 install
# with nothing to download or install.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
